package movie.recommender.backend.models;

import javax.persistence.*;

@Entity
@Table(name = "movie")
public class Movie {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long movieId;

    @Column
    String name;
    //Picture picture
    @Column
    String description;
    @Column
    String imdbLink;

    @Column
    int happyScore;
    @Column
    int sadScore;
    @Column
    int funnyScore;

    public Movie(){
        this.happyScore=0;
        this.sadScore=0;
        this.funnyScore=0;
    }

    //Autogenerated getters & setters
    public long getMovieId() {
        return movieId;
    }

    public void setMovieId(long movieId) {
        this.movieId = movieId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImdbLink() {
        return imdbLink;
    }

    public void setImdbLink(String imdbLink) {
        this.imdbLink = imdbLink;
    }

    public int getHappyScore() {
        return happyScore;
    }

    public void setHappyScore(int happyScore) {
        this.happyScore = happyScore;
    }

    public int getSadScore() {
        return sadScore;
    }

    public void setSadScore(int sadScore) {
        this.sadScore = sadScore;
    }

    public int getFunnyScore() {
        return funnyScore;
    }

    public void setFunnyScore(int funnyScore) {
        this.funnyScore = funnyScore;
    }


    //Update scores
    public void updateHappyScore(int happyScore){
        this.happyScore = (this.happyScore+happyScore)/2;
    }

    public void updateSadScore(int sadScore){
        this.sadScore = (this.sadScore+sadScore)/2;
    }

    public void updateFunnyScore(int funnyScore){
        this.funnyScore = (this.funnyScore+funnyScore)/2;
    }
}